---
- name: Prepare MicroSD for Raspberry Pi
  hosts: 127.0.0.1 
  vars:
    image_ver: 20.04.3
    image_name: ubuntu-{{image_ver}}-preinstalled-server-arm64+raspi
    work_dir: /tmp
    microsd_name: sdX
    microsd_mount_path: /mnt/microsd
    host_id: 9
    github_username: yunir
  tasks:
    - name: Check image exist
      stat:
        path: "{{work_dir}}/{{image_name}}.img"
      register: image_file

    - name: Download compressed image
      get_url: 
        url: https://cdimage.ubuntu.com/releases/{{image_ver}}/release/{{image_name}}.img.xz
        dest: "{{work_dir}}/{{image_name}}.img.xz"
      when: not image_file.stat.exists
    
    - name: Uncompress the image
      command:
        cmd: unxz {{work_dir}}/{{image_name}}.img.xz
        creates: "{{work_dir}}/{{image_name}}.img" 

    - name: Check microsd exist
      stat: 
        path: /dev/{{microsd_name}}
      register: microsd

    - name: Flash image to microsd
      command:
        cmd: dd if={{work_dir}}/{{image_name}}.img of=/dev/{{microsd_name}} bs=4M
      when: microsd.stat.exists
      become: yes

    - name: Create directory to mount microsd's boot partition
      file: 
        path: "{{microsd_mount_path}}"
        state: directory
      become: yes

    - name: Mount microsd's boot partition to directory
      mount:
        path: "{{microsd_mount_path}}"
        src: /dev/{{microsd_name}}1
        fstype: vfat
        state: mounted
      become: yes

    - name: Substitute cloud-init network configuration on boot partition
      template: 
        dest: "{{microsd_mount_path}}"
        src: ../files/network-config
      become: yes

    - name: Get public ssh key
      uri:
        url: https://github.com/{{github_username}}.keys
        return_content: yes
      register: public_ssh_key_response

    - name: Substitute cloud-init user data on boot partition 
      template: 
        dest: "{{microsd_mount_path}}"
        src: ../files/user-data
      vars:
        public_ssh_key: "{{public_ssh_key_response.content}}"
      become: yes

    - name: Unmount microsd's boot partition
      mount:
        path: "{{microsd_mount_path}}" 
        state: absent
      become: yes
...
